name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - qa
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Skip Tests
        run: echo "No tests configured"

      - name: Build Application
        run: echo "Build Completed"

  deploy-dev:
    name: Deploy to Development
    needs: build
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Dev Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            cd /home/sourav/form-app
            git checkout dev
            git pull origin dev
            npm install
            pm2 restart form-app

  deploy-qa:
    name: Deploy to QA
    needs: build
    if: github.ref == 'refs/heads/qa'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to QA Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.QA_HOST }}
          username: ${{ secrets.QA_USER }}
          key: ${{ secrets.QA_SSH_KEY }}
          script: |
            cd /home/sourav/form-app
            git checkout qa
            git pull origin qa
            npm install
            pm2 restart form-app

  deploy-prod:
    name: Deploy to Production
    needs: build
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd /home/sourav/form-app
            git checkout prod
            git pull origin prod
            npm install
            pm2 restart form-app
